apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-deployment
  labels:
    app: animals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animals
  template:
    metadata:
      labels:
        app: animals
    spec:
      containers:
        - name: animals
          image: nagapparohit/animals:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: animal-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: animal-configmap
                  key: SPRING_ZIPKIN_BASEURL
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: animal-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: animal-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          resources:
            limits:
              memory: 256Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: animals-service
spec:
  selector:
    app: animals
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
